# Generated by Django 3.0.4 on 2020-04-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of department', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('building_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_displayer_app.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField(blank=True, null=True)),
                ('End_date', models.DateTimeField(blank=True, null=True)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('building_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_displayer_app.Building')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_displayer_app.Room')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_displayer_app.EventType')),
            ],
        ),
    ]
